WTF_CSRF_ENABLED = True
SECRET_KEY = 'you-will-never-guess'
SOLR_URI = 'http://localhost:8983/solr/'
NEWS_COLLECTION_INSTANCE = 'newsArticleCollection'

WIKI_ARTICLE_INSTANCE = 'wikiArticleCollection'
SNIPPET_FRAGMENT_SIZE = 100
SNIPPET_MAX = 10
SNIPPET_OPENING = "<mark>"
SNIPPET_CLOSING = "</mark>"
SNIPPET_GENERATION = "true"
SNIPPET_FIELDS = "*"

INDEX_KEYWORD_GENERATION = False